export const theme = {
  colors: {
    blue: "var(--color-blue)",
    red: "var(--color-red)",
    redLight: "var(--color-red-light)",
    blueDark: "var(--color-blue-dark)",
    blueMid: "var(--color-blue-mid)",
    green: "var(--color-green)",
    greenDark: "var(--color-green-dark)",
    blueLight: "var(--color-blue-light)",
    white: "var(--color-white)",
    black: "var(--color-black)",
    grey: "var(--color-grey)",
    greyMid: "var(--color-grey-mid)",
    button: "var(--color-button)",
    textDefault: "var(--color-text-default)",
    textAlt: "var(--color-text-alt)",
  },
  fonts: {
    family: "var(--font-family)",
    headingFamily: "var(--font-heading-family)",
    weightLight: "var(--font-weight-light)",
    weightDefault: "var(--font-weight-default)",
    weightSemibold: "var(--font-weight-semibold)",
    weightBold: "var(--font-weight-bold)",
    weightHeadingBold: "var(--font-weight-heading-bold)",
    sizeXDisplay: "var(--font-size-x-display)",
    sizeDisplay: "var(--font-size-display)",
    sizeXxLarge: "var(--font-size-xx-large)",
    sizeXLarge: "var(--font-size-x-large)",
    sizeLarge: "var(--font-size-large)",
    sizeMedium: "var(--font-size-medium)",
    sizeDefault: "var(--font-size-default)",
    sizeSmall: "var(--font-size-small)",
    sizeXSmall: "var(--font-size-x-small)",
    sizeXxSmall: "var(--font-size-xx-small)",
    lineHeightText: "var(--lineheight-text)",
    lineHeightHeading: "var(--lineheight-heading)",
  },
  borderRadius: {
    xSmall: "var(--border-radius-x-small)",
    small: "var(--border-radius-small)",
    medium: "var(--border-radius-medium)",
    large: "var(--border-radius-large)",
    circle: "var(--border-radius-circle)",
  },
  borderWidth: {
    hairline: "var(--border-width-hairline)",
    thin: "var(--border-width-thin)",
    thick: "var(--border-width-thick)",
  },
  boxShadow: "var(--box-shadow)",
  grid: {
    columnGap: "var(--grid-column-gap)",
    rowGap: "var(--grid-row-gap)",
  },
  maxWidth: "var(--max-width)",
  spacing: {
    xxSmall: "var(--spacing-xx-small)",
    xSmall: "var(--spacing-x-small)",
    small: "var(--spacing-small)",
    default: "var(--spacing)",
    medium: "var(--spacing-medium)",
    large: "var(--spacing-large)",
    xLarge: "var(--spacing-x-large)",
    xxLarge: "var(--spacing-xx-large)",
    xxxLarge: "var(--spacing-xxx-large)",
    xxxxLarge: "var(--spacing-xxxx-large)",
  },
  duration: {
    instantly: "var(--duration-instantly)",
    immediately: "var(--duration-immediately)",
    quickly: "var(--duration-quickly)",
    promptly: "var(--duration-promptly)",
    slowly: "var(--duration-slowly)",
  },
};

export type KobotTheme = typeof theme;
