name: Verify Code

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js lts/iron
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron
    - run: npm install
    - run: npm run build
    - run: npm run format:check
    - run: npm run test:ci
      env:
        CI: true
