name: Release Main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js lts/iron
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - run: npm install
      - run: npm run build
        env:
          CI: true

      - name: Create Release
        id: create_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
